import React from 'react';
import { UserResult } from '@/models/strength';

interface AdminCertificateProps {
  userName: string;
  results: UserResult;
  date: string;
  certificateId: string;
}

const AdminCertificate: React.FC<AdminCertificateProps> = ({
  userName,
  results,
  date,
  certificateId
}) => {
  // Validate the results data structure
  const hasValidResults = results && 
                        results.topStrengths && 
                        Array.isArray(results.topStrengths) && 
                        results.topStrengths.length > 0;
  
  return (
    <div 
      data-certificate
      className="w-[210mm] h-[297mm] bg-white p-12 flex flex-col relative font-inter"
      style={{ 
        boxSizing: 'border-box',
      }}
    >
      {/* Header with Logo */}
      <div className="flex justify-between items-start mb-12">
        <div className="w-32">
          <div className="text-2xl font-bold text-inuka-crimson">SA</div>
          <div className="text-xs text-gray-500 mt-1">Strengths Africa</div>
        </div>
        <div className="text-right">
          <div className="text-sm text-gray-500">Report ID</div>
          <div className="font-mono text-sm">{certificateId}</div>
        </div>
      </div>

      {/* Title Section */}
      <div className="mb-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-3">Strength Discovery Report</h1>
        <div className="h-1 w-24 bg-inuka-crimson mb-4"></div>
        <div className="flex justify-between items-center text-gray-600">
          <div>
            <span className="font-medium">Participant:</span> {userName}
          </div>
          <div>
            <span className="font-medium">Date:</span> {date}
          </div>
        </div>
      </div>
      
      {/* Summary Section */}
      <div className="bg-gray-50 rounded-lg p-6 mb-8">
        <h2 className="text-xl font-semibold text-gray-800 mb-6">
          Top 5 Strengths Analysis
        </h2>
        
        <div className="space-y-4">
          {hasValidResults ? (
            results.topStrengths.map((item, index) => (
              <div key={item.strength.id || index} className="bg-white rounded-lg p-4 shadow-sm border border-gray-100">
                <div className="flex items-start justify-between">
                  <div className="flex items-start space-x-4">
                    <div className="w-10 h-10 rounded-full bg-gray-50 flex items-center justify-center border border-gray-200">
                      <span className="text-gray-700 font-medium">{index + 1}</span>
                    </div>
                    <div>
                      <h3 className="font-semibold text-gray-900 mb-1">
                        {item.strength.name}
                      </h3>
                      <div className="flex items-center space-x-2">
                        <span className="px-2 py-1 bg-gray-100 rounded text-xs font-medium text-gray-600">
                          {item.strength.category.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
                        </span>
                        <span className="text-sm text-gray-500">
                          Score: <span className="font-semibold text-gray-700">{item.score.toFixed(1)}</span>
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))
          ) : (
            <div className="text-center py-8 text-gray-500 bg-white rounded-lg border border-gray-100">
              <p>No strength data available</p>
            </div>
          )}
        </div>
      </div>
      
      {/* Footer */}
      <div className="mt-auto">
        <div className="h-px bg-gray-200 mb-6"></div>
        <div className="flex justify-between items-center text-sm text-gray-500">
          <div>
            <span className="font-medium">Generated by:</span> Strengths Africa Admin
          </div>
          <div>
            <span className="font-medium">Version:</span> 1.0
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminCertificate; 