// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuaszulmvjmnxzcdlfhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1YXN6dWxtdmptbnh6Y2RsZmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjA5NjYsImV4cCI6MjA2Mjc5Njk2Nn0.CzK8JT0J6ege2wOtcQYKRhtZJb5sl__FQOuX96N0ruw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);